### PR TITLE
Fix decoding two encoded chars after each other

### PR DESCRIPTION
**Pull request by tholu**
Related issue: #14

- Update dependencies for the project
- Add failing test
- Fix test by doing two decoding rounds: First decode 3-byte-characters, then 1-byte-characters. Doing this at the same time is not feasible, as this leads to the problem described in #14 with 2 1-byte-characters after each other.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Hi @tholu thank you very much for the effort you've put on this! I really appreciate it!

Just one thing, I can see a lot of code style changes, editor-specific file changes, and code changes in the same PR. It's hard to build a conversation this way usign Github, it becomes very noise and too much context switching. In the spirit to make it easy to review and focus on the priorities, is it possible to split this in multiple PRs handling each a single thing?

For example, in this order:

1 PR just with the minimum code to fix #14
1 PR to fix dependencies
1 PR for removing the Eclipse-specific files
1 PR to change the code style from tabs to spaces
n PRs to do any other refactoring you want to introduce

This way we can talk about each change and I can still be aware of the codebase without getting distracted by a lot of changes all at once. I know this requires some work in your side, but I think it will be helpful to the project.

Is that ok? Thanks! again!

**Comment by tholu** [comment]
Thanks for your quick feedback! Some Codestyle changes were not really necessary, I‘m sorry for that! Out of a habit, I let IDEA do the default formatting. 

As the project is quite out-of-shape, I needed to update the dependencies to get the tests running initially (and also consequently fix Travis, which is currently failing). 

I will try to separate the changes as much as possible, and would start with the dependency cleanup and Travis fix, so the tests are running again. Then the test and fix for #14. Then any other changes.

**Comment by FagnerMartinsBrack** [comment]
> would start with the dependency cleanup and Travis fix, so the tests are running again


Awesome! I agree with that. Making it work, then make it better ;D

**Comment by tholu** [comment]
@FagnerMartinsBrack First splitted PR is in #19 - this should get the Travis build fixed and current tests running.

**Comment by tholu** [comment]
Closing in favor of #21.

**Pull request closed without merging**
